//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartamento()
        {
            this.Contrato = new HashSet<Contrato>();
            this.FotoApartamento = new HashSet<FotoApartamento>();
            this.Mantenimiento = new HashSet<Mantenimiento>();
            this.Cita = new HashSet<Cita>();
        }
    
        public int ID_Apartamento { get; set; }
        public string Codigo_Apartamento { get; set; }
        public int ID_Edificio { get; set; }
        public int Piso { get; set; }
        public double Metros_Cuadrados { get; set; }
        public Nullable<int> Cantidad_Habitantes { get; set; }
        public Nullable<int> Cant_Sanitarios { get; set; }
        public Nullable<bool> Disponible { get; set; }
    
        public virtual Edificio Edificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotoApartamento> FotoApartamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
    }
}
