//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartamento()
        {
            this.Contrato = new HashSet<Contrato>();
            this.Mantenimiento = new HashSet<Mantenimiento>();
        }
    
        public int ID_Apartamento { get; set; }
        public string Codigo_Apartamento { get; set; }
        public int ID_Edificio { get; set; }
        public int Piso { get; set; }
        public double Metros_Cuadrados { get; set; }
        public Nullable<int> Cantidad_Habitantes { get; set; }
        public Nullable<int> Cant_Sanitarios { get; set; }
        public Nullable<bool> Disponible { get; set; }
    
        public virtual Edificio Edificio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contrato> Contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
    }
}
