//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aviso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aviso()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int ID_Aviso { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public System.DateTime Fecha_Publicacion { get; set; }
        public string Autor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
