//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int ID_Cita { get; set; }
        public int ID_Usuario { get; set; }
        public int ID_Apartamento { get; set; }
        public System.DateTime FechaCita { get; set; }
        public string Mensaje { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Apartamento Apartamento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
