//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int ID_Mantenimiento { get; set; }
        public int ID_Apartamento { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha_Mantenimiento { get; set; }
        public double Costo { get; set; }
        public string Tipo { get; set; }
    
        public virtual Apartamento Apartamento { get; set; }
    }
}
