//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimiento
    {
        public int ID_Mantenimiento { get; set; }
        public int ID_Apartamento { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha_Mantenimiento { get; set; }
        public double Costo { get; set; }
        public string Tipo { get; set; }
    
        public virtual Apartamento Apartamento { get; set; }
    }
}
