//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SistemaAlquilerEntities1 : DbContext
    {
        public SistemaAlquilerEntities1()
            : base("name=SistemaAlquilerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apartamento> Apartamento { get; set; }
        public virtual DbSet<AreaRecreativa> AreaRecreativa { get; set; }
        public virtual DbSet<Aviso> Aviso { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<Edificio> Edificio { get; set; }
        public virtual DbSet<FotoApartamento> FotoApartamento { get; set; }
        public virtual DbSet<Mantenimiento> Mantenimiento { get; set; }
        public virtual DbSet<Pago> Pago { get; set; }
        public virtual DbSet<TRol> TRol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual int sp_InsertUsuario(string nombre, string cedula, string telefono, string contrasenna, string correo, Nullable<System.DateTime> fecha_Nacimiento)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var fecha_NacimientoParameter = fecha_Nacimiento.HasValue ?
                new ObjectParameter("Fecha_Nacimiento", fecha_Nacimiento) :
                new ObjectParameter("Fecha_Nacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertUsuario", nombreParameter, cedulaParameter, telefonoParameter, contrasennaParameter, correoParameter, fecha_NacimientoParameter);
        }
    }
}
