//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int ID_Pago { get; set; }
        public int ID_Contrato { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
        public double Monto_Pago { get; set; }
        public string Metodo_Pago { get; set; }
        public string Comprobante_URL { get; set; }
        public string Estado { get; set; }
        public string Numero_SINPE { get; set; }
    
        public virtual Contrato Contrato { get; set; }
    }
}
