//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoProgramacion.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int ID_Pago { get; set; }
        public int ID_Contrato { get; set; }
        public System.DateTime Fecha_Pago { get; set; }
        public double Monto_Pago { get; set; }
        public string Metodo_Pago { get; set; }
    
        public virtual Contrato Contrato { get; set; }
    }
}
